-- Retire legacy browser-callable SECURITY DEFINER RPCs after the v5 admin API became canonical.
-- Keep current v5/admin dashboard and functional user RPCs intact.

-- Legacy generic admin mutation/list endpoints are no longer used by the frontend.
revoke execute on function public.admin_approve_profile(uuid, text) from authenticated;
revoke execute on function public.admin_list_pending_access_requests() from authenticated;
revoke execute on function public.admin_list_profiles() from authenticated;
revoke execute on function public.admin_reject_profile(uuid) from authenticated;
revoke execute on function public.admin_update_profile(uuid, text, text, text, text[], text, text, text, text, text, text) from authenticated;

-- v3 admin API and its authorization helper are superseded by v5.
revoke execute on function public.forjados_admin_approve_profile_v3(uuid, text) from authenticated;
revoke execute on function public.forjados_admin_list_pending_access_requests_v3() from authenticated;
revoke execute on function public.forjados_admin_list_profiles_v3() from authenticated;
revoke execute on function public.forjados_admin_reject_profile_v3(uuid) from authenticated;
revoke execute on function public.forjados_admin_update_profile_v3(uuid, text, text, text, text[], text, text, text, text, text, text) from authenticated;
revoke execute on function public.forjados_current_user_can_manage_v3() from authenticated;

-- v4 admin API and its authorization helper are superseded by v5.
revoke execute on function public.forjados_admin_approve_profile_v4(uuid, text) from authenticated;
revoke execute on function public.forjados_admin_list_pending_access_requests_v4() from authenticated;
revoke execute on function public.forjados_admin_list_profiles_v4() from authenticated;
revoke execute on function public.forjados_admin_reject_profile_v4(uuid) from authenticated;
revoke execute on function public.forjados_admin_update_profile_v4(uuid, text, text, text, text[], text, text, text, text, text, text) from authenticated;
revoke execute on function public.forjados_admin_is_authorized_v4() from authenticated;

-- Audit entries are generated by trusted database routines/triggers, never directly by browsers.
revoke execute on function public.create_audit_log(text, text, text, text, jsonb) from authenticated;
